language = {
    "en": {
        "syntax": 'Syntax: "Combat/Blank"',
        "syntax2": 'Syntax: "Blank/Combat"',
        "start": "[green]Let's start the game![/green]\n",
        "help": "Plus - combat\nMinus - blank\n",
        "shot": "Shot?: ",
        "combat_gone": "\n[red]The combat is gone![/red]\n",
        "blank_gone": "\n[red]The blank are gone![/red]\n",
        "result": lambda combat, blank: f"Combat: {combat}\nBlank: {blank}",
        "chance_c": lambda chance_c: f"Combat chance: {chance_c}%",
        "chance_b": lambda chance_b: f"Blank chance: {chance_b}%",
        "round_over": "\n[yellow]The round is over![/yellow]\n",
        "history": "History: ",
        "continue": "Continue? (yes or no): ",
        "overlay_ask": "Do you want to launch the overlay?",
        "overlay": "[green]The overlay is running![/green]",
        "overlayE": "[red]ERROR! Your system does not support overlays![/red]",
        "language": "[green]The language is set![/green]",
        "pre_update": "Would you like to receive pre-releases?",
        "style": "Select a syntax style: ",
        "smart": "Would you like to enable the smart shot prediction feature?",
        "shot_history": "Do you want to enable round history?",
    },
    "ru": {
        "syntax": 'Синтаксис: "Боевые/Холостые"',
        "syntax2": 'Синтаксис: "Холостые/Боевые"',
        "start": "[green]Начинаем игру![/green]\n",
        "help": "Плюс - боевой\nМинус - холостой\n",
        "shot": "Выстрел?: ",
        "combat_gone": "\n[red]Боевых нет![/red]\n",
        "blank_gone": "\n[red]Холостых нет![/red]\n",
        "result": lambda combat, blank: f"Боевые: {combat}\nХолостые: {blank}",
        "chance_c": lambda chance_c: f"Шанс на боевой: {chance_c}%",
        "chance_b": lambda chance_b: f"Шанс на холостой: {chance_b}%",
        "round_over": "\n[yellow]Раунд окончен![/yellow]\n",
        "history": "История: ",
        "continue": "Продолжить? (yes or no): ",
        "overlay_ask": "Вы хотите запустить оверлей?",
        "overlay": "[green]Оверлей запущен![/green]",
        "overlayE": "\n[red]ОШИБКА! Ваша система не поддерживает оверлей![/red]",
        "language": "[green]Язык настроен![/green]",
        "pre_update": "Хотите получать предварительные обновления?",
        "style": "Выберите стиль синтаксиса: ",
        "smart": "Вы хотите включить функцию умного прогнозирования выстрела?",
        "shot_history": "Вы хотите включить историю раунда?",
    },
}
